from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from typing import List

from .. import database, models, schemas
from ..utils import security

router = APIRouter(prefix="/api/requests", tags=["Request Records"])

# Standardizes how statuses appear on the frontend.
def simplify_status(raw_status: str) -> str:
    if not raw_status:
        return "Pending"
        
    status_lower = raw_status.lower()
    if "approved" in status_lower:
        return "Approved"
    elif "reject" in status_lower: 
        return "Rejected"
    else:
        # Keep detailed 'Pending' statuses intact for accurate pipeline tracking.
        return raw_status

# Gathers every request a coordinator has ever made (MoUs, Permissions, Venues) into one cohesive list.
@router.get("/all", response_model=List[schemas.RequestRecordResponse])
def get_all_user_requests(
    db: Session = Depends(database.get_db),
    current_user: models.User = Depends(security.get_current_user)
):
    # Check that the user is a coordinator, as this specific route powers the coordinator dashboard.
    if current_user.role != "coordinator":
        raise HTTPException(status_code=403, detail="Only coordinators can view this dashboard.")

    unified_records = []

    # 1. Gather all MoU requests created by this user.
    mous = db.query(models.MoURequest).filter(models.MoURequest.coordinator_id == current_user.id).all()
    for mou in mous:
        unified_records.append({
            "id": mou.id,
            "type": "MOU",
            "date": mou.created_at.strftime("%b %d, %Y") if mou.created_at else "N/A", 
            "details": mou.organization_name,
            "purpose": mou.purpose, 
            "document_url": mou.document_url, 
            "status": simplify_status(mou.status),
            "raw_status": mou.status,
            "comments": mou.comments
        })

    # 2. Gather all Permission Letters generated by this user's club.
    permissions = db.query(models.PermissionLetter).filter(models.PermissionLetter.club_id == current_user.id).all()
    permission_gen_ids = [p.generated_id for p in permissions if p.generated_id]

    for perm in permissions:
        created = getattr(perm, 'created_at', None)
        unified_records.append({
            "id": perm.id,
            "type": "PERMISSION",
            "date": created.strftime("%b %d, %Y") if created else "N/A", 
            "event_date": perm.date,
            "time": perm.time,
            "reason": perm.reason,
            "details": perm.event_name,
            "status": simplify_status(perm.status),
            "raw_status": perm.status,
            "comments": perm.comments,
            "generated_id": perm.generated_id
        })

    # 3. Gather all Venue Bookings that correspond to the permissions fetched above.
    if permission_gen_ids:
        venues = db.query(models.VenueBooking).filter(
            models.VenueBooking.permission_letter_id.in_(permission_gen_ids)
        ).all()
        
        for venue in venues:
            created = getattr(venue, 'created_at', None)
            unified_records.append({
                "id": venue.id,
                "type": "VENUE",
                "date": created.strftime("%b %d, %Y") if created else "N/A", 
                "event_date": venue.date,
                "time": venue.time,
                "expected_attendees": getattr(venue, 'expected_attendees', 0),
                "description": getattr(venue, 'description', 'N/A'),
                "details": venue.event_title,
                "status": simplify_status(venue.status),
                "raw_status": venue.status,
                "comments": venue.comments
            })

    # 4. Sort the finalized combined list chronologically, with the most recent items at the top.
    unified_records.sort(key=lambda x: x["date"], reverse=True)

    return unified_records

# Dictates exactly which status an authority is responsible for reviewing.
AUTHORITY_STATUS_MAP = {
    "gensec": "Pending GenSec",
    "president": "Pending President",
    "facad": "Pending FacAd",
    "adsa": "Pending ADSA",
}

# --- HELPER LOGIC FOR AUTHORITY PERMISSIONS ---
# Determines what an authority has currently on their plate, and what they have already dealt with historically.
# --- HELPER LOGIC FOR AUTHORITY PERMISSIONS ---
# Determines what an authority has currently on their plate, and what they have already dealt with historically.
def get_authority_pipeline_data(user_role: str):
    target_status = AUTHORITY_STATUS_MAP.get(user_role)
    PIPELINE = ["Pending GenSec", "Pending President", "Pending FacAd", "Pending ADSA", "Approved"]
    
    try:
        user_index = PIPELINE.index(target_status)
        statuses_beyond = PIPELINE[user_index + 1:]
    except ValueError:
        user_index = -1
        statuses_beyond = []

    rejected_by_me = f"Rejected by {user_role}"

    # Assesses if a particular status represents an action this authority has already completed.
    def is_history(status: str) -> bool:
        if not status: return False
        if status in statuses_beyond: return True
        if status == rejected_by_me: return True
        if status.startswith("Rejected by "):
            rejecter_role = status.replace("Rejected by ", "")
            rejecter_status = AUTHORITY_STATUS_MAP.get(rejecter_role)
            # If someone AFTER me rejected it, it's still in my history because I approved it first
            if rejecter_status in PIPELINE and PIPELINE.index(rejecter_status) > user_index:
                return True
        return False

    # NEW: Translates the global pipeline status into a personalized status for the viewing authority
    def format_status_for_viewer(status: str) -> str:
        if status == target_status:
            return status # Still pending for them, show exactly as is
        if status == rejected_by_me:
            return "Rejected"
        if is_history(status):
            return "Approved" # If it passed them and they didn't reject it, they approved it!
        return status

    return target_status, is_history, format_status_for_viewer
# Gathers requests across all clubs that are currently waiting for this specific authority to approve or reject.
@router.get("/pending")
def get_pending_requests_for_authority(
    db: Session = Depends(database.get_db),
    current_user: models.User = Depends(security.get_current_user)
):
    if current_user.role not in AUTHORITY_STATUS_MAP:
        raise HTTPException(status_code=403, detail="Not authorized.")
        
    target_status, _, _ = get_authority_pipeline_data(current_user.role)
    unified_records = []
    
    # Check for pending MoUs.
    for mou in db.query(models.MoURequest).filter(models.MoURequest.status == target_status).all():
        club = db.query(models.User).filter(models.User.id == mou.coordinator_id).first()
        unified_records.append({
            "id": mou.id, "club_name": club.username if club else "Unknown Club",
            "type": "MOU", "event_title": mou.organization_name, "expected_attendees": 0,
            "details": mou.purpose, "permission_letter_id": "N/A", "status": mou.status,
            "timestamp": mou.created_at.isoformat() if mou.created_at else "N/A",
            "document_url": getattr(mou, 'document_url', None) 
        })
        
    # Check for pending Permissions.
    for perm in db.query(models.PermissionLetter).filter(models.PermissionLetter.status == target_status).all():
        club = db.query(models.User).filter(models.User.id == perm.club_id).first()
        unified_records.append({
            "id": perm.id, "club_name": club.username if club else "Unknown Club",
            "type": "PERMISSION", "event_title": perm.event_name, "expected_attendees": 0,
            "details": perm.reason, "permission_letter_id": "N/A", "status": perm.status, "timestamp": perm.date
        })
        
    # Check for pending Venue Bookings.
    for venue in db.query(models.VenueBooking).filter(models.VenueBooking.status == target_status).all():
        club_name, perm = "Unknown Club", db.query(models.PermissionLetter).filter(models.PermissionLetter.generated_id == venue.permission_letter_id).first()
        if perm:
            club = db.query(models.User).filter(models.User.id == perm.club_id).first()
            if club: club_name = club.username

        unified_records.append({
            "id": venue.id, "club_name": club_name, "type": "VENUE", "event_title": venue.event_title,
            "expected_attendees": venue.expected_attendees, "details": venue.description,
            "permission_letter_id": venue.permission_letter_id, "status": venue.status, "timestamp": venue.date
        })
        
    return unified_records

# Gathers requests across all clubs that this specific authority has already processed in the past.
@router.get("/history")
def get_history_for_authority(
    db: Session = Depends(database.get_db),
    current_user: models.User = Depends(security.get_current_user)
):
    if current_user.role not in AUTHORITY_STATUS_MAP:
        raise HTTPException(status_code=403, detail="Not authorized.")

    _, is_history, format_status = get_authority_pipeline_data(current_user.role)
    unified_records = []

    # Filter MoUs that represent past work.
    for mou in db.query(models.MoURequest).all():
        if is_history(mou.status):
            club = db.query(models.User).filter(models.User.id == mou.coordinator_id).first()
            unified_records.append({
                "id": mou.id, "club_name": club.username if club else "Unknown",
                "type": "MOU", "event_title": mou.organization_name, "status": format_status(mou.status),
                "timestamp": mou.created_at.isoformat() if mou.created_at else "N/A",
                "details": mou.purpose, # <--- ADD THIS
                "document_url": getattr(mou, 'document_url', None) # <--- ADD THIS
            })
            
    # Filter Permissions that represent past work.
    for perm in db.query(models.PermissionLetter).all():
        if is_history(perm.status):
            club = db.query(models.User).filter(models.User.id == perm.club_id).first()
            unified_records.append({
                "id": perm.id, "club_name": club.username if club else "Unknown",
                "type": "PERMISSION", "event_title": perm.event_name,"status": format_status(perm.status), "timestamp": perm.date,
                "details": perm.reason
            })
            
    # Filter Venues that represent past work.
    for venue in db.query(models.VenueBooking).all():
        if is_history(venue.status):
            club_name, perm = "Unknown", db.query(models.PermissionLetter).filter(models.PermissionLetter.generated_id == venue.permission_letter_id).first()
            if perm:
                club = db.query(models.User).filter(models.User.id == perm.club_id).first()
                if club: club_name = club.username
            unified_records.append({
                "id": venue.id, "club_name": club_name, "type": "VENUE", "event_title": venue.event_title,
                "status": format_status(venue.status), "timestamp": venue.date,
                "details": venue.description, # <--- ADD THIS
                "expected_attendees": venue.expected_attendees, # <--- ADD THIS
                "permission_letter_id": venue.permission_letter_id # <--- ADD THIS
            })
            
    unified_records.sort(key=lambda x: x["timestamp"] if x["timestamp"] else "", reverse=True)
    return unified_records

# Gathers pending and historical requests for one specific club. Usually called when viewing that club's profile.
@router.get("/club/{club_id}")
def get_club_requests_for_authority(
    club_id: int,
    db: Session = Depends(database.get_db),
    current_user: models.User = Depends(security.get_current_user)
):
    if current_user.role not in AUTHORITY_STATUS_MAP:
        raise HTTPException(status_code=403, detail="Not authorized.")

    club = db.query(models.Club).filter(models.Club.id == club_id).first()
    if not club: raise HTTPException(status_code=404, detail="Club not found")
        
    coordinator_id = club.user_id
    target_status, is_history, format_status = get_authority_pipeline_data(current_user.role)
    unified_records = []

    # Checks if a request falls into either pending status or historical processed status for this user.
    def is_relevant(status: str) -> bool:
        return status == target_status or is_history(status)

    mous = db.query(models.MoURequest).filter(models.MoURequest.coordinator_id == coordinator_id).all()
    for mou in mous:
        if is_relevant(mou.status):
            unified_records.append({
                "id": mou.id, "type": "MOU", "event_title": mou.organization_name, "expected_attendees": 0,
                "details": mou.purpose, "status": format_status(mou.status), "timestamp": mou.created_at.strftime("%Y-%m-%d") if mou.created_at else ""
            })

    permissions = db.query(models.PermissionLetter).filter(models.PermissionLetter.club_id == coordinator_id).all()
    permission_gen_ids = [p.generated_id for p in permissions if p.generated_id]
    for perm in permissions:
        if is_relevant(perm.status):
            unified_records.append({
                "id": perm.id, "type": "PERMISSION", "event_title": perm.event_name, "expected_attendees": 0,
                "details": perm.reason, "status": format_status(perm.status), "timestamp": perm.date or ""
            })

    if permission_gen_ids:
        venues = db.query(models.VenueBooking).filter(models.VenueBooking.permission_letter_id.in_(permission_gen_ids)).all()
        for venue in venues:
            if is_relevant(venue.status):
                unified_records.append({
                    "id": venue.id, "type": "VENUE", "event_title": venue.event_title, "expected_attendees": venue.expected_attendees,
                    "details": venue.description, "status": format_status(venue.status), "timestamp": venue.date or ""
                })

    unified_records.sort(key=lambda x: x["timestamp"], reverse=True)
    return unified_records